[Unit]
RequiresMountsFor=/home/khoi
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=
ExecStart=/home/khoi/mrfix/supervise.sh
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
